targets:
  $default:
    sources:
      - $package$
      - lib/**
      - swagger/**
    builders:
      rentalworks|rw_builder:
        enabled: false
        options:
          input_folder: "swagger/"
          output_folder: "lib/swagger/"
      chopper_generator:
        enabled: false
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        enabled: true
        options:
          with_base_url: false
          #with_converter: true
          #use_required_attribute_for_headers: true
          #ignore_headers: false
          #use_default_null_for_lists: false
          #use_inheritance: false
          #build_only_models: true
          #model_postfix: "Dto"
          #use_path_for_request_names: true
          #include_if_null:
          #  enabled: true
          #  value: false
          input_folder: "swagger/"
          output_folder: "generated_code/"
          #enums_case_sensitive: true
          #default_values_map:
          #  - type_name: int
          #    default_value: "36"
          #  - type_name: String
          #    default_value: ""
          #exclude_paths:
          #  - "/pet/findByStatus"
          #default_header_values_map:
          #  - header_name: "X-Rate-Limit"
          #    default_value: "12121212"
          #  - header_name: "Api_key"
          #    default_value: "some_api_key"
          #response_override_value_map:
          #  - url: "/store/inventory"
          #    method: get
          #    overridden_value: "List<dynamic>"

builders:
  rentalworks|rw_builder:
    import: "builder/builder.dart"
    builder_factories: ["rentalWorksBuilder"]
    build_extensions:
      ".swagger": [".swagger.dart", ".models.dart", ".converter.dart"]
    build_to: source
    auto_apply: root_package
    runs_before: ["chopper_generator"]
