name: rentalworks
description: A RentalWorks (inventory control) API library for Dart developers.
version: 1.1.0
homepage: https://github.com/point-source/dart_rentalworks

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chopper: ^4.0.1
  collection: ^1.15.0
  json_annotation: ^4.1.0
  meta: ^1.7.0

dev_dependencies:
  args: ^2.2.0
  build_runner: ^2.0.6
  chopper_generator: ^4.0.1
  json_serializable: ^4.1.3
  lints: ^1.0.1
  swagger_dart_code_generator: ^2.0.8+1
  test: ^1.14.4

dependency_overrides:
  swagger_dart_code_generator:
    git:
      url: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator.git
      ref: version/2.1.0
