name: rentalworks
description: A RentalWorks (inventory control) API library for Dart developers.
version: 5.0.1
homepage: https://github.com/point-source/dart_rentalworks

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  chopper: ^6.1.1
  collection: ^1.17.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  http: ^0.13.5
  json_serializable: ^6.1.5
  lints: ^2.0.1
  swagger_dart_code_generator: ^2.10.4
  test: ^1.24.2