targets:
  rentalworks_builder:rentalworks_builder:
    sources:
      - $package$
      - lib/$lib$
      - swagger/json/**
    builders:
      rentalworks_builder:
        enabled: True
        options:
          input_folder: "swagger/json/"
          output_folder: "swagger/"

builders:
  rentalworks_builder:
    import: "package:rentalworks_builder/rentalworks_builder.dart"
    builder_factories: ["rentalWorksBuilder"]
    build_extensions:
      "$lib$": [".swagger"]
    build_to: source
    auto_apply: dependents
    runs_before: ["swagger_dart_code_generator:swagger_dart_code_generator"]
