name: rentalworks_builder
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build: ^2.0.3

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.0.6
  lints: ^1.0.1
  test: ^1.14.4
